# Site settings
title: Start Hacking
stylized: StartHacking.org
email: team@hackmit.org
description: >
  A guide to setting up a development environment on any platform for any
  project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://starthacking.org" # the base hostname & protocol for your site
github: "https://github.com/starthacking/starthacking.github.io"
contributing: "http://starthacking.org/contributing.html"

license: "https://github.com/starthacking/starthacking.github.io/blob/master/LICENSE.txt"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Permalinks
permalink: /:title/

# Settings
timezone: America/New_York
analytics:
  tracking_id: UA-63828172-14

# Excludes
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt

